"""
Build script: parses USDA SR Legacy CSVs and writes data/seed_products.py.
Run once: python data/_build_seed_products.py

Source data: FoodData_Central_sr_legacy_food_csv_2018-04
"""

import csv
import math
import os

DATA_DIR = "/Users/donna/Downloads/FoodData_Central_sr_legacy_food_csv_2018-04"
OUT_PATH = os.path.join(os.path.dirname(__file__), "seed_products.py")

# fdc_id → slug, is_pure_sugar
TARGETS = {
    "173410": ("butter",              False),
    "172336": ("canola_oil",          False),
    "171412": ("coconut_oil",         False),
    "170567": ("almonds",             False),
    "170187": ("walnuts",             False),
    "173905": ("oats",                False),
    "169761": ("all_purpose_flour",   False),
    "168833": ("brown_sugar",         True),
    "169655": ("granulated_sugar",    True),
    "169640": ("honey",               True),
    "168165": ("raisins",             False),
    "171723": ("dried_cranberries",   False),
    "172470": ("peanut_butter",       False),
    "170273": ("dark_chocolate",      False),
    "172217": ("whole_milk",          False),
    "171287": ("egg_whole_raw",       False),
    "173177": ("whey_protein_isolate",False),
    "170554": ("chia_seeds",          False),
    "169414": ("flaxseed",            False),
    "173468": ("salt",                False),
}

# USDA nutrient_id → (field_name, unit)
NUTRIENT_MAP = {
    "1008": "energy_kcal",
    "1003": "protein_g",
    "1004": "total_fat_g",
    "1258": "saturated_fat_g",
    "1257": "trans_fat_g",
    "1253": "cholesterol_mg",
    "1005": "total_carbohydrate_g",
    "1079": "dietary_fiber_g",
    "2000": "total_sugars_g",
    "1093": "sodium_mg",
    "1092": "potassium_mg",
    "1087": "calcium_mg",
    "1089": "iron_mg",
    "1114": "vitamin_d_mcg",
}

FIELD_ORDER = [
    "energy_kcal",
    "protein_g",
    "total_fat_g",
    "saturated_fat_g",
    "trans_fat_g",
    "cholesterol_mg",
    "total_carbohydrate_g",
    "dietary_fiber_g",
    "total_sugars_g",
    "added_sugars_g",
    "sodium_mg",
    "potassium_mg",
    "calcium_mg",
    "iron_mg",
    "vitamin_d_mcg",
]


def round_half_up(x: float, decimals: int = 2) -> float:
    """floor(x / increment + 0.5) — never Python round()."""
    factor = 10 ** decimals
    return math.floor(x * factor + 0.5) / factor


def load_foods() -> dict[str, str]:
    foods = {}
    with open(f"{DATA_DIR}/food.csv") as f:
        for row in csv.DictReader(f):
            if row["fdc_id"] in TARGETS:
                foods[row["fdc_id"]] = row["description"].strip()
    return foods


def load_food_nutrients(target_fdc_ids: set[str]) -> dict[str, dict[str, float]]:
    """fdc_id → {field_name: amount_per_100g}

    food_nutrient.nutrient_id matches nutrient.id directly —
    the NUTRIENT_MAP keys are those id values.
    """
    result: dict[str, dict[str, float]] = {fid: {} for fid in target_fdc_ids}

    with open(f"{DATA_DIR}/food_nutrient.csv") as f:
        for row in csv.DictReader(f):
            fdc_id = row["fdc_id"].strip()
            if fdc_id not in target_fdc_ids:
                continue
            nutrient_id = row["nutrient_id"].strip()
            field = NUTRIENT_MAP.get(nutrient_id)
            if field is None:
                continue
            try:
                amount = float(row["amount"])
            except (ValueError, KeyError):
                amount = 0.0
            result[fdc_id][field] = amount

    return result


def build_entry(fdc_id: str, description: str, slug: str,
                is_pure_sugar: bool, raw_nutrients: dict[str, float]) -> dict:
    entry: dict = {
        "fdc_id": int(fdc_id),
        "description": description,
        "is_pure_sugar": is_pure_sugar,
    }
    missing = []
    for field in FIELD_ORDER:
        if field == "added_sugars_g":
            entry[field] = 0.0  # not in SR Legacy; always 0
            continue
        raw = raw_nutrients.get(field)
        if raw is None:
            entry[field] = 0.0
            missing.append(field)
        else:
            entry[field] = round_half_up(raw, 4)
    entry["_missing_nutrients"] = missing
    return entry


def fmt_float(v: float) -> str:
    # Show up to 4 decimal places, strip trailing zeros
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if "." in s else s + ".0"


def write_output(entries: dict[str, dict]) -> None:
    lines = [
        '"""',
        "Seed products — USDA SR Legacy 2018 data, per 100g.",
        "Auto-generated by data/_build_seed_products.py.",
        "",
        "Nutrient IDs sourced from USDA FoodData Central SR Legacy release.",
        "added_sugars_g is not present in SR Legacy; set to 0.0 for all entries.",
        'is_pure_sugar=True: sugar/honey ingredients (flag for label rounding logic).',
        '"""',
        "",
        "SEED_PRODUCTS: dict[str, dict] = {",
    ]

    for slug, entry in entries.items():
        fdc_id = entry["fdc_id"]
        desc = entry["description"]
        is_pure_sugar = entry["is_pure_sugar"]
        missing = entry.get("_missing_nutrients", [])

        lines.append(f'    "{slug}": {{')
        lines.append(f'        "fdc_id": {fdc_id},')
        lines.append(f'        "description": "{desc}",')
        lines.append(f'        "is_pure_sugar": {is_pure_sugar},')
        lines.append( '        # --- nutrients per 100g ---')
        for field in FIELD_ORDER:
            val = entry[field]
            comment = ""
            if field in missing:
                comment = "  # not in SR Legacy for this food"
            elif field == "added_sugars_g":
                comment = "  # not in SR Legacy; set 0.0"
            lines.append(f'        "{field}": {fmt_float(val)},{comment}')
        lines.append("    },")

    lines.append("}")
    lines.append("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT_PATH}")


def main() -> None:
    fdc_ids = set(TARGETS.keys())
    foods = load_foods()
    raw_data = load_food_nutrients(fdc_ids)

    entries: dict[str, dict] = {}
    for fdc_id, (slug, is_pure_sugar) in TARGETS.items():
        desc = foods.get(fdc_id, f"FDC {fdc_id}")
        raw = raw_data.get(fdc_id, {})
        entry = build_entry(fdc_id, desc, slug, is_pure_sugar, raw)
        if entry["_missing_nutrients"]:
            print(f"  {slug}: missing {entry['_missing_nutrients']}")
        entries[slug] = entry

    # Sort by slug for stable output
    entries = dict(sorted(entries.items()))
    write_output(entries)


if __name__ == "__main__":
    main()
